<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250226215058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add work_days and work_shifts tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE work_days (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, work_shift_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_12274D5E6EC53652 ON work_days (work_shift_id)');
        $this->addSql('CREATE TABLE work_shifts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(7) NOT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE work_days ADD CONSTRAINT FK_12274D5E6EC53652 FOREIGN KEY (work_shift_id) REFERENCES work_shifts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE work_days DROP CONSTRAINT FK_12274D5E6EC53652');
        $this->addSql('DROP TABLE work_days');
        $this->addSql('DROP TABLE work_shifts');
    }
}
